name: dio_security_and_caching
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  retrofit: ^4.5.0
  retrofit_generator: ^9.3.0
  dio_cache_interceptor: ^4.0.3
  dio_cookie_manager: ^3.2.0
  logger: ^2.6.0
  freezed_annotation: ^3.1.0
  freezed: ^3.0.6
  json_annotation: ^4.9.0
  flutter_secure_storage: ^4.2.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  injectable_generator: ^2.7.0
  go_router: ^16.0.0
  pretty_dio_logger: ^1.4.0
  crypto: ^3.0.6
  flutter_hooks: ^0.21.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
